config/routes.rb
Myapp::Application.routes.draw do
  constraints(:id => /[^\/]+/) do
    resources :bookmarks do
      get 'search'
      get 'ausearch'
    end  
    match 'bookmarks/search/:id' => 'bookmarks#search'
    match 'bookmarks/ausearch/:id' => 'bookmarks#ausearch'
  end
  

  root :to => 'bookmarks#index'

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  attr_accessible :details, :title,:created_at, :id, :updated_at,:burl
  validates :title, :length => { :minimum => 1,:message=>"Title : Please Enter Title"}
  validates :burl, :format => { :with => /((([A-Za-z]{3,9}:(?:\/\/)?)(?:[-;:&=\+\$,\w]+@)?[A-Za-z0-9.-]+|(?:www.|[-;:&=\+\$,\w]+@)[A-Za-z0-9.-]+)((?:\/[\+~%\/.\w-_]*)?\??(?:[-\+=&;%@.\w_]*)#?(?:[\w]*))?)/,
    :message=>"URL : Invalid URL (ex: http://xyz.com)" }

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  # GET /bookmarks
  # GET /bookmarks.json
  def index
    @bookmarks = Bookmark.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bookmarks }
    end
  end

  # GET /bookmarks/1
  # GET /bookmarks/1.json
  def show
    @bookmark = Bookmark.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bookmark }
    end
  end

  # GET /bookmarks/new
  # GET /bookmarks/new.json
  def new
    @bookmark = Bookmark.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bookmark }
    end
  end

  # GET /bookmarks/1/edit
  def edit
    @bookmark = Bookmark.find(params[:id])
  end

  # POST /bookmarks
  # POST /bookmarks.json
  def create
    @bookmark = Bookmark.new(params[:bookmark])

    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully created.' }
        format.json { render json: @bookmark, status: :created, location: @bookmark }
      else
        format.html { render action: "new" }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bookmarks/1
  # PUT /bookmarks/1.json
  def update
    @bookmark = Bookmark.find(params[:id])

    respond_to do |format|
      params[:bookmark].delete :silent
      if @bookmark.update_attributes(params[:bookmark])
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookmarks/1
  # DELETE /bookmarks/1.json
  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    respond_to do |format|
      format.html { redirect_to bookmarks_url }
      format.json { head :no_content }
    end
  end
  # GET /bookmarks/search/1
  # GET /bookmarks/search/1.json
  def search
    @bookmarks = Bookmark.where("LOWER(details) like ? or LOWER(title) like ? or LOWER(burl) like ? ", "%" + params[:id].downcase + "%" , "%" + params[:id].downcase + "%", "%" + params[:id].downcase + "%")
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bookmarks }
    end
  end
  def ausearch
    @bookmarks = Bookmark.find_by_sql("select title as query from bookmarks where title like '%" + params[:q].downcase + "%' union select details as query from bookmarks where details like '%" + params[:q].downcase + "%' union select burl as query from bookmarks where burl like '%" + params[:q].downcase + "%'")
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bookmarks }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/btags_helper.rb
module BtagsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/bookmarks/_form.html.erb
<%= form_for(@bookmark) do |f| %>
  <% if @bookmark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bookmark.errors.count, "error") %> prohibited this bookmark from being saved:</h2>

      <ul>
      <% @bookmark.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :details %><br />
    <%= f.text_field :details %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookmarks/ausearch.html.erb
<%= @bookmarks.to_json.html_safe -%>

app/views/bookmarks/edit.html.erb
<h1>Editing bookmark</h1>

<%= render 'form' %>

<%= link_to 'Show', @bookmark %> |
<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/index.html.erb
<div id="bookmarks"></div>

<script type="text/javascript">
  $(function() {
    // Blog is the app name
    window.router = new Myapp.Routers.BookmarksRouter({bookmarks: <%= @bookmarks.to_json.html_safe -%>});
    Backbone.history.start();
  });
  $("#searchQ").autocomplete("/bookmarks/ausearch/1", {
        width: 320,
        dataType: 'json',
        highlight: false,
        scroll: true,
        scrollHeight: 300,
        parse: function(data) {
        		var q=$("#searchQ").val();
                var array = new Array();
                var str=","
                var sep=","

                for(var i=0;i<data.length;i++)
                {
                	
                	if(data[i].query.indexOf(",")> -1) {
                		var temp= data[i].query.split(",");
	                	for (var j=0;j<temp.length;j++){
	                		if(temp[j].toLowerCase().indexOf(q) > -1 && str.indexOf(","+temp[j].toLowerCase() + ",")== -1){
								array[array.length] = {"data": temp[j],"result": temp[j]};	
								str += temp[j] + sep;
						
							}
	                	}
                	} else
                	{
                		if(str.indexOf(","+data[i].query.toLowerCase()+ ",") == -1){
                			array[array.length] = {"data": data[i].query, "result": data[i].query};	
                				str += data[i].query + sep ;
						
						}
                	}
            	}
                return array;
        },

        formatItem: function(row) {                     
        	return row;
        }
    });
</script>

app/views/bookmarks/new.html.erb
<h1>New bookmark</h1>

<%= render 'form' %>

<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/search.html.erb
<%= @bookmarks.to_json.html_safe -%>

app/views/bookmarks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @bookmark.title %>
</p>

<p>
  <b>Details:</b>
  <%= @bookmark.details %>
</p>


<%= link_to 'Edit', edit_bookmark_path(@bookmark) %> |
<%= link_to 'Back', bookmarks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar">
              <div class="navbar-inner">
                <div class="container">
                  <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </a>
                  <a class="brand" href="#">Title</a>
                  <div class="nav-collapse">
                    <ul class="nav">
                      <li class="active"><a href="#">Home</a></li>
                      <li><a href="#/new">New</a></li>
                    </ul>
                    <form class="navbar-search pull-left" id="searchform">
                      <input type="text" class="search-query span2" placeholder="Search" id="searchQ" />
                    </form>
                  </div><!-- /.nav-collapse -->
                </div>
              </div><!-- /navbar-inner -->
            </div>
<%= yield %>
<script type="text/javascript">
var lastQuery
$("#searchQ").keyup(function(e){
   if (e.which == 13)
    $('#searchform').submit();

})
$('#searchform').submit(function() {
  lastQuery=$("#searchQ").val()
  window.location="#/search/" + lastQuery
  $("#searchQ").val("")
  return false;
});
</script>
</body>
</html>